# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Release to Maven Central

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - id: install-secret-key
      name: Install gpg secret key
      run: |
        cat <(echo -e "${{ secrets.GPG_CODE_SIGNING_KEY }}") | gpg --batch --import
        gpg --list-secret-keys --keyid-format LONG
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Test with code coverage
      run: ./gradlew check jacocoTestReport
    - name: Run upload
      run: bash <(curl -s https://codecov.io/bash)
    - name: Report Codacy
      run: bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r service/build/jacoco.xml
      env:
        CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_KEY }}
