# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Release to Maven Central

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - id: install-secret-key
      name: Install gpg secret key
      run: |
        cat <(echo -e "${{ secrets.GPG_CODE_SIGNING_KEY }}") | gpg --batch --import
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew publish -Psigning.secretKeyRingFile=/home/runner/.gnupg/pubring.kbx -Psigning.keyId="${{ secrets.GPG_KEY_ID }}" -Psigning.password="${{ secrets.GPG_PASSWORD }}" -PuserName="${{ secrets.MVN_USERNAME }}" -Ppw="${{ secrets.MVN_PASSWORD }}"
